In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset/train.csv", keep_default_na=False,na_values=["NA", np.nan, ""])

In [3]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
df = df.drop("Id", axis=1)

In [5]:
df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# Data Preprocessing

In [6]:
df["Alley"] = df["Alley"].fillna("NA")

In [7]:
df.columns[df.isna().any()].tolist()

['LotFrontage',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [8]:
na_columns = ["Alley", "BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2", "FireplaceQu", "GarageType", "GarageFinish", "GarageQual", "GarageCond", "PoolQC", "Fence", "MiscFeature"]

In [9]:
df[na_columns] = df[na_columns].fillna("NA")

In [10]:
df.columns[df.isna().any()].tolist()

['LotFrontage', 'MasVnrType', 'MasVnrArea', 'Electrical', 'GarageYrBlt']

In [11]:
df["MasVnrType"] = df["MasVnrType"].fillna("None")

In [12]:
df.columns[df.isna().any()].tolist()

['LotFrontage', 'MasVnrArea', 'Electrical', 'GarageYrBlt']

In [13]:
def replace_with_mean(df, column):
    mean = df[column].mean()
    df[column] = df[column].fillna(mean)
    return df

In [14]:
df = replace_with_mean(df, column="LotFrontage")

In [15]:
df = replace_with_mean(df, column="MasVnrArea")

In [16]:
df.columns[df.isna().any()].tolist()

['Electrical', 'GarageYrBlt']

In [17]:
df["Electrical"] = df["Electrical"].fillna("SBrkr")

In [18]:
df["GarageYrBlt"] = df["GarageYrBlt"].fillna(2005)

In [19]:
df["MSSubClass"].value_counts()

MSSubClass
20     536
60     299
50     144
120     87
30      69
160     63
70      60
80      58
90      52
190     30
85      20
75      16
45      12
180     10
40       4
Name: count, dtype: int64

In [20]:
MS_SubclassMapping = {20:0, 30:1, 40:2, 45:3, 50:4, 60:5, 70: 6, 75: 7, 80: 8, 85:9, 90: 10, 120: 11, 150: 12, 160: 13, 180: 14, 190: 15}

In [21]:
df["MSSubClass"].replace(MS_SubclassMapping, inplace=True)

/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/1627894109.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["MSSubClass"].replace(MS_SubclassMapping, inplace=True)

In [22]:
df["MSZoning"].value_counts()

MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

In [23]:
MSZoning_Mapping = {"A":0, "C":1, "FV":2, "I":3, "RH":4, "RL":5, "RP":6, "RM":7}
df["MSZoning"].replace(MSZoning_Mapping, inplace=True)

/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2277950651.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["MSZoning"].replace(MSZoning_Mapping, inplace=True)

In [24]:
category_list = ["Street", "Alley","LotShape", "LandContour", "Utilities", "LotConfig", "LandSlope" ,"Neighborhood", "Condition1" , "Condition2"]
drop_list = ["Alley", ""]

In [27]:
utilites_map = {"Utilities" : 0, "NoSewr": 1, "NoSeWa":2, "ELO":3}
exterior_list = {key: index for key, index in enumerate(["AsbShng", "AsphShn", "BrkComm", "BrkFace", "CBlock", "CemntBd", "HdBoard", "ImStucc", "MetalSd", "Other", "Plywood", "PreCast", "Stone", "Stucco", "VinylSd", "Wd Sdng", "WdShing"])}
masvnrtype_map = {index:key for key, index in enumerate(["BrkCmn", "BrkFace", "CBlock", "None", "Stone"])}
exterior_quality_map = kitchen_quak_map = {index:key for key, index in enumerate(["Ex", "Gd", "TA", "Fa", "Po"])}
bsmt_quality_map = bsmt_cond_map  = {index:key for key, index in enumerate(["Ex", "Gd", "TA", "Fa", "Po", "NA"])}
functional_map = {index:key for key, index in enumerate(["Typ", "Min1", "Min2", "Mod", "Maj1", "Maj2", "Sev", "Sal"])}
pool_qc_map = {index:key for key, index in enumerate(["Ex", "Gd", "TA", "Fa", "NA"])}
misc_feature_map = {index:key for key, index in enumerate(["Elev", "Gar2", "Othr", "Shed", "TenC", "NA"])}
sales_type_feature_map = {index:key for key, index in enumerate(["WD", "CWD", "VWD", "New", "COD", "Con", "COD", "Con", "ConLw" ,"ConLI", "ConLD", "Oth"])}

In [246]:
df["SaleCondition"].value_counts()

SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

In [207]:
df["ExterQual"] = df["Street"].astype("category")

In [194]:
#df["Alley"] = df["Alley"].astype("category")

In [195]:
#df["LotShape"] = df["LotShape"].astype("category")