In [161]:
import pandas as pd
import numpy as np

In [162]:
df = pd.read_csv("dataset/train.csv", keep_default_na=False,na_values=["NA", np.nan, ""])

In [163]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [164]:
df = df.drop("Id", axis=1)

In [165]:
df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# Data Preprocessing

In [166]:
df["Alley"] = df["Alley"].fillna("NA")

In [167]:
df.columns[df.isna().any()].tolist()

['LotFrontage',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [168]:
na_columns = ["Alley", "BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2", "FireplaceQu", "GarageType", "GarageFinish", "GarageQual", "GarageCond", "PoolQC", "Fence", "MiscFeature"]

In [169]:
df[na_columns] = df[na_columns].fillna("NA")

In [170]:
df.columns[df.isna().any()].tolist()

['LotFrontage', 'MasVnrType', 'MasVnrArea', 'Electrical', 'GarageYrBlt']

In [171]:
df["MasVnrType"] = df["MasVnrType"].fillna("None")

In [172]:
df.columns[df.isna().any()].tolist()

['LotFrontage', 'MasVnrArea', 'Electrical', 'GarageYrBlt']

In [173]:
def replace_with_mean(df, column):
    mean = df[column].mean()
    df[column] = df[column].fillna(mean)
    return df

In [174]:
df = replace_with_mean(df, column="LotFrontage")

In [175]:
df = replace_with_mean(df, column="MasVnrArea")

In [176]:
df.columns[df.isna().any()].tolist()

['Electrical', 'GarageYrBlt']

In [177]:
df["Electrical"] = df["Electrical"].fillna("SBrkr")

In [178]:
df["GarageYrBlt"] = df["GarageYrBlt"].fillna(2005)

In [179]:
df["MSSubClass"].value_counts()

MSSubClass
20     536
60     299
50     144
120     87
30      69
160     63
70      60
80      58
90      52
190     30
85      20
75      16
45      12
180     10
40       4
Name: count, dtype: int64

In [180]:
MS_SubclassMapping = {20:0, 30:1, 40:2, 45:3, 50:4, 60:5, 70: 6, 75: 7, 80: 8, 85:9, 90: 10, 120: 11, 150: 12, 160: 13, 180: 14, 190: 15}

In [181]:
MSZoning_Mapping = {"A":0, "C":1, "FV":2, "I":3, "RH":4, "RL":5, "RP":6, "RM":7}

In [182]:
utilites_map = {"AllPub" : 0, "NoSewr": 1, "NoSeWa":2, "ELO":3}
condition_2_map = {key: index for key, index in enumerate(df["Condition1"].astype("category").cat.categories)}
exterior_list = {key: index for key, index in enumerate(["AsbShng", "AsphShn", "BrkComm", "BrkFace", "CBlock", "CemntBd", "HdBoard", "ImStucc", "MetalSd", "Other", "Plywood", "PreCast", "Stone", "Stucco", "VinylSd", "Wd Sdng", "WdShing"])}
masvnrtype_map = {index:key for key, index in enumerate(["BrkCmn", "BrkFace", "CBlock", "None", "Stone"])}
exterior_quality_map = kitchen_qual_map = {index:key for key, index in enumerate(["Ex", "Gd", "TA", "Fa", "Po"])}
bsmt_quality_map = bsmt_cond_map  = {index:key for key, index in enumerate(["Ex", "Gd", "TA", "Fa", "Po", "NA"])}
functional_map = {index:key for key, index in enumerate(["Typ", "Min1", "Min2", "Mod", "Maj1", "Maj2", "Sev", "Sal"])}
pool_qc_map = {index:key for key, index in enumerate(["Ex", "Gd", "TA", "Fa", "NA"])}
misc_feature_map = {index:key for key, index in enumerate(["Elev", "Gar2", "Othr", "Shed", "TenC", "NA"])}
sales_type_feature_map = {index:key for key, index in enumerate(["WD", "CWD", "VWD", "New", "COD", "Con", "COD", "Con", "ConLw" ,"ConLI", "ConLD", "Oth"])}

In [183]:
condition_2_map

{0: 'Artery',
 1: 'Feedr',
 2: 'Norm',
 3: 'PosA',
 4: 'PosN',
 5: 'RRAe',
 6: 'RRAn',
 7: 'RRNe',
 8: 'RRNn'}

In [184]:
#df["Alley"] = df["Alley"].astype("category")

In [185]:
#df["LotShape"] = df["LotShape"].astype("category")

In [186]:
df["SaleCondition"].value_counts()

SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

In [187]:
def get_proprocessed_data():

    category_list = ["Street", "Alley", "LotShape", "LandContour", "LotConfig", "LandSlope", "BldgType", "HouseStyle", "RoofStyle", "RoofMatl", "ExterCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2", "Heating", "HeatingQC", "CentralAir", "Electrical", "FireplaceQu", "GarageType", "GarageFinish", "GarageQual", "GarageCond", "Fence", "SaleCondition"]
    df["MSSubClass"] = df["MSSubClass"].replace(MS_SubclassMapping)
    df["MSZoning"] = df["MSZoning"].replace(MSZoning_Mapping)
    df["Utilities"] = df["Utilities"].replace(utilites_map)
    df["Condition1"] = df["Condition1"].replace(condition_2_map)
    df["Condition2"] = df["Condition2"].replace(condition_2_map)
    df["Exterior1st"] = df["Exterior1st"].replace(exterior_list)
    df["Exterior2nd"] = df["Exterior2nd"].replace(exterior_list)
    df["MasVnrType"] = df["MasVnrType"].replace(masvnrtype_map)
    df["ExterQual"] = df["ExterQual"].replace(exterior_quality_map)
    df["BsmtQual"] = df["BsmtQual"].replace(bsmt_quality_map)
    df["BsmtCond"] = df["BsmtCond"].replace(bsmt_cond_map)
    df["KitchenQual"] = df["KitchenQual"].replace(kitchen_qual_map)
    df["Functional"] = df["Functional"].replace(functional_map)
    df["PoolQC"] = df["PoolQC"].replace(pool_qc_map)
    df["MiscFeature"] = df["MiscFeature"].replace(misc_feature_map)
    df["SaleType"] = df["SaleType"].replace(sales_type_feature_map)

    for category in category_list:
        df[category] = df[category].astype("category")
        df[category] = df[category].cat.codes

In [188]:
get_proprocessed_data()

/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2731493125.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Utilities"] = df["Utilities"].replace(utilites_map)
/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2731493125.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["MasVnrType"] = df["MasVnrType"].replace(masvnrtype_map)
/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2731493125.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["ExterQual"] = df["ExterQual"].replace(exterior_quality_map)
/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2731493125.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["BsmtQual"] = df["BsmtQual"].replace(bsmt_quality_map)
/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2731493125.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["BsmtCond"] = df["BsmtCond"].replace(bsmt_cond_map)
/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2731493125.py:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["KitchenQual"] = df["KitchenQual"].replace(kitchen_qual_map)
/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2731493125.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Functional"] = df["Functional"].replace(functional_map)
/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2731493125.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["PoolQC"] = df["PoolQC"].replace(pool_qc_map)
/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2731493125.py:18: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["MiscFeature"] = df["MiscFeature"].replace(misc_feature_map)
/var/folders/gr/jldz2p6n4k9c6wvsc1fm2lch0000gn/T/ipykernel_93458/2731493125.py:19: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["SaleType"] = df["SaleType"].replace(sales_type_feature_map)

In [189]:
df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,5,5,65.0,8450,1,1,3,3,0,4,...,0,4,4,5,0,2,2008,0,4,208500
1,0,5,80.0,9600,1,1,3,3,0,2,...,0,4,4,5,0,5,2007,0,4,181500
2,5,5,68.0,11250,1,1,0,3,0,4,...,0,4,4,5,0,9,2008,0,4,223500
3,6,5,60.0,9550,1,1,0,3,0,0,...,0,4,4,5,0,2,2006,0,0,140000
4,5,5,84.0,14260,1,1,0,3,0,2,...,0,4,4,5,0,12,2008,0,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,5,5,62.0,7917,1,1,3,3,0,4,...,0,4,4,5,0,8,2007,0,4,175000
1456,0,5,85.0,13175,1,1,3,3,0,4,...,0,4,2,5,0,2,2010,0,4,210000
1457,6,5,66.0,9042,1,1,3,3,0,4,...,0,4,0,3,2500,5,2010,0,4,266500
1458,0,5,68.0,9717,1,1,3,3,0,4,...,0,4,4,5,0,4,2010,0,4,142125
1459,0,5,75.0,9937,1,1,3,3,0,4,...,0,4,4,5,0,6,2008,0,4,147500

In [190]:
df["Street"].value_counts()

Street
1    1454
0       6
Name: count, dtype: int64